language: php

php:
  - 5.3.3
  - 5.4

matrix:
  allow_failures:
    - php: 5.4

before_install:
    - composer selfupdate
    - composer update --dev --verbose
    
script:
    - phpunit --coverage-text