language: php

php:
  - 5.3.3
  - 5.3  
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.4

before_install:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install
    
script:
    - phpunit --coverage-text